/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#091426',
        'primary-container':          '#1e293b',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#8590a6',
        'secondary':                  '#9d4300',
        'secondary-container':        '#fd761a',
        'on-secondary':               '#ffffff',
        'surface':                    '#f9f9ff',
        'surface-dim':                '#cfdaf2',
        'surface-bright':             '#f9f9ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f0f3ff',
        'surface-container':          '#e7eeff',
        'surface-container-high':     '#dee8ff',
        'surface-container-highest':  '#d8e3fb',
        'surface-variant':            '#d8e3fb',
        'on-surface':                 '#111c2d',
        'on-surface-variant':         '#45474c',
        'outline':                    '#75777d',
        'outline-variant':            '#c5c6cd',
        'error':                      '#ba1a1a',
        'error-container':            '#ffdad6',
        'on-error':                   '#ffffff',
        'tertiary-container':         '#5a0008',
        'on-tertiary-container':      '#ff5250',
        'background':                 '#f9f9ff',
        'on-background':              '#111c2d',
        'inverse-surface':            '#263143',
        'inverse-on-surface':         '#ecf1ff',
        'inverse-primary':            '#bcc7de',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        sans:     ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      boxShadow: {
        'ghost': '0px 20px 40px rgba(17, 28, 45, 0.06)',
        'ghost-md': '0px 12px 28px rgba(17, 28, 45, 0.10)',
      },
    },
  },
  plugins: [],
};
