/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#0a0f1a',   
        'primary-container':          '#1b2538',
        'on-primary':                 '#ffffff',
        'on-primary-container':       '#a3aec2',  
        'secondary':                  '#b34700',   
        'secondary-container':        '#ff7a1f',   
        'on-secondary':               '#ffffff',
        'surface':                    '#ffffff', 
        'surface-dim':                '#d0d9ec',
        'surface-bright':             '#ffffff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#f4f6ff',
        'surface-container':          '#e9f0ff',
        'surface-container-high':     '#dce6ff',
        'surface-container-highest':  '#d2def9',
        'surface-variant':            '#c9d4f0',
        'on-surface':                 '#0d1726',
        'on-surface-variant':         '#3a3c41',
        'outline':                    '#5f6167',
        'outline-variant':            '#8e9199',
        'error':                      '#c11212',
        'error-container':            '#ffd9d6',
        'on-error':                   '#ffffff',
        'tertiary-container':         '#6a0010', 
        'on-tertiary-container':      '#ff6a68', 
        'background':                 '#ffffff',
        'on-background':              '#0d1726',
        'inverse-surface':            '#1f2a3d',
        'inverse-on-surface':         '#f2f6ff',
        'inverse-primary':            '#aeb9d4',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body:     ['Inter', 'sans-serif'],
        label:    ['Inter', 'sans-serif'],
        sans:     ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      boxShadow: {
        'ghost': '0px 20px 40px rgba(13, 23, 38, 0.08)',
        'ghost-md': '0px 12px 28px rgba(13, 23, 38, 0.12)',
      },
    },
  },
  plugins: [],
};
